# Site Settings
baseurl: ""
url: "https://lafer-m.github.io/"

# Blog Settings
theme_settings:
  title: Blog of mrzzjiy
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/smile.png
    username: Mrzzjiy
    description: based on Grape-Theme!.
    experience:
      - start: 2017-05-03
        end: 2018-05-06
        experience: company name, title
    skills:
      - skill: golang
        value: 85  # Percent value
      - skill: python
        value:  80

  # Icons
  icons:
    email:  mrzzjiy@gmail.com
    linkedin:  # Full URL 
    github: lafer-m
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
